# Site settings
title: Matthew Bush
email: bushmat4@gmail.com
baseurl: ""
url: "http://mtthwbsh.com"
twitter_username: MTTHWBSH
github_username:  MTTHWBSH
dribbble_username: MTTHWBSH
linkedin_username: matthewallenbush
email: bushmat4@gmail.com

# Build settings
markdown: kramdown
sass:
    style: :compressed
    sass_dir: _sass
